[project]
name = "00-setup-and-tooling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jamal Fox", email = "Fox.Jamal@outlook.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
00-setup-and-tooling = "00_setup_and_tooling:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
